#Create a patient entity

POST http://localhost:4000/patients
Content-Type: application/json


{
"name":"Kafka Consumer with billing account",
  "email": "test21@kafkaConsumer.com",
  "address": "123 street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2010-09-09"
}